server:
  port : 5000
spring:
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: redis-11257.c290.ap-northeast-1-2.ec2.cloud.redislabs.com
      port: 11257
      username: default
      password: "!Q@W3e4r"

jwt-variables:
  KEY: WEBSOCKET_POC
  ISSUER: CNCBI
  EXPIRES_ACCESS_TOKEN_MINUTE: 30
  EXPIRES_REFRESH_TOKEN_MINUTE: 300000